// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLe9zJQCYZkjMUyQSskH9P5GYqFJY2yKw',
    appId: '1:94229908832:web:e92a8f6da72da2afb32205',
    messagingSenderId: '94229908832',
    projectId: 'supplementstore-63c82',
    authDomain: 'supplementstore-63c82.firebaseapp.com',
    storageBucket: 'supplementstore-63c82.firebasestorage.app',
    measurementId: 'G-FTZFMPC1FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAABryRj9QvGmiiw7S8m3FweV8jnREsRl0',
    appId: '1:94229908832:android:5fbc9e27a37f267cb32205',
    messagingSenderId: '94229908832',
    projectId: 'supplementstore-63c82',
    storageBucket: 'supplementstore-63c82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLapSbUTW_YKT-jXj7etoiSor6GKKGeJU',
    appId: '1:94229908832:ios:85278330d5356191b32205',
    messagingSenderId: '94229908832',
    projectId: 'supplementstore-63c82',
    storageBucket: 'supplementstore-63c82.firebasestorage.app',
    iosBundleId: 'com.example.gymSupplementStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLapSbUTW_YKT-jXj7etoiSor6GKKGeJU',
    appId: '1:94229908832:ios:85278330d5356191b32205',
    messagingSenderId: '94229908832',
    projectId: 'supplementstore-63c82',
    storageBucket: 'supplementstore-63c82.firebasestorage.app',
    iosBundleId: 'com.example.gymSupplementStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLe9zJQCYZkjMUyQSskH9P5GYqFJY2yKw',
    appId: '1:94229908832:web:422ce90841b3fbe0b32205',
    messagingSenderId: '94229908832',
    projectId: 'supplementstore-63c82',
    authDomain: 'supplementstore-63c82.firebaseapp.com',
    storageBucket: 'supplementstore-63c82.firebasestorage.app',
    measurementId: 'G-9SN4F7296B',
  );
}
